#!/usr/bin/env Rscript
# =============================================================================
# Regenerates renv.lock and docker/sysreqs.txt for the peek-raab-base image.
# This is the reusable tool for the (deliberate, gated) ~yearly dependency bump.
# See docker/RENV_MIGRATION_PLAN.md §7 (Steps 1-2) and §8.
#
# Run INSIDE a Noble R container, with the repo mounted at /work, e.g.:
#
#   docker run --rm --platform linux/amd64 -v "$PWD":/work -w /tmp/proj \
#     rocker/r-ver:4.4.3 bash -lc '
#       apt-get update -qq && apt-get install -y --no-install-recommends \
#         build-essential cmake pkg-config libssl-dev libsasl2-dev \
#         libcurl4-openssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev \
#         libfribidi-dev libfreetype-dev libpng-dev libtiff5-dev libjpeg-dev \
#         libglpk-dev libgmp-dev libv8-dev zlib1g-dev libbz2-dev >/dev/null &&
#       Rscript /work/docker/generate-deps.R'
#
# The apt list above is only a BOOTSTRAP so this generation step works; the
# AUTHORITATIVE list is what this script writes to docker/sysreqs.txt (from pak).
#
# Outputs written to the repo (REPO_ROOT, default /work):
#   renv.lock, .Rprofile, renv/activate.R, renv/.gitignore, docker/sysreqs.txt
# =============================================================================

SNAPSHOT  <- Sys.getenv("PPM_SNAPSHOT", "2026-06-01")   # amd64 reproducibility anchor
PLATFORM  <- "ubuntu-24.04"                              # noble
REPO_ROOT <- Sys.getenv("REPO_ROOT", "/work")

repo <- sprintf("https://packagemanager.posit.co/cran/__linux__/noble/%s", SNAPSHOT)
options(
  repos = c(CRAN = repo),
  # Ensure PPM serves Linux binaries (not source) for this platform:
  HTTPUserAgent = sprintf(
    "R/%s R (%s)", getRversion(),
    paste(getRversion(), R.version$platform, R.version$arch, R.version$os)
  )
)

# Top-level package set used by the RAAB7 report path (RAAB7_reporter.Rmd + wrapper).
# Keep in sync with docker/RENV_MIGRATION_PLAN.md §4.
pkgs <- c(
  "rmarkdown", "readxl", "knitr", "tinytex", "kableExtra", "RColorBrewer",
  "RCurl", "jsonlite", "tidyverse", "stringr", "treemap", "maditr", "here",
  "extrafont", "float", "systemfonts", "svglite"
)

message(">> R ", getRversion(), " | PPM snapshot ", SNAPSHOT, " | ", PLATFORM)
message(">> Installing tooling (renv, pak) ...")
install.packages(c("renv", "pak"))

## ---- 1) System requirements for the FULL dependency closure -----------------
message(">> Resolving system requirements via pak ...")
sr <- pak::pkg_sysreqs(pkgs, sysreqs_platform = PLATFORM)

sys_pkgs <- tryCatch(
  sort(unique(unlist(sr$packages$system_packages))),
  error = function(e) character()
)
install_scripts <- tryCatch(sr$install_scripts, error = function(e) character())

sysreqs_path <- file.path(REPO_ROOT, "docker", "sysreqs.txt")
writeLines(c(
  "# GENERATED by docker/generate-deps.R - do not edit by hand.",
  sprintf("# R %s | PPM snapshot %s | platform %s", getRversion(), SNAPSHOT, PLATFORM),
  sprintf("# Top-level packages: %s", paste(pkgs, collapse = ", ")),
  "#",
  "# Apt packages for the full dependency closure (one per line).",
  "# Consume in Dockerfile.base with e.g.:",
  "#   grep -vE '^\\s*#|^\\s*$' docker/sysreqs.txt | xargs apt-get install -y --no-install-recommends",
  "#",
  if (length(sys_pkgs)) sys_pkgs else "# (pak reported no system requirements)",
  "",
  "# --- reference: pak install_scripts ---",
  paste0("# ", install_scripts)
), sysreqs_path)
message(">> Wrote ", sysreqs_path, " (", length(sys_pkgs), " apt packages)")

## ---- 2) renv lockfile -------------------------------------------------------
message(">> Initialising renv + installing packages (PPM binaries) ...")
renv::init(bare = TRUE)
renv::install(pkgs)
renv::snapshot(type = "all", prompt = FALSE)

copy_to_repo <- function(from, to_rel) {
  to <- file.path(REPO_ROOT, to_rel)
  dir.create(dirname(to), showWarnings = FALSE, recursive = TRUE)
  file.copy(from, to, overwrite = TRUE)
}
copy_to_repo("renv.lock",        "renv.lock")
copy_to_repo(".Rprofile",        ".Rprofile")
copy_to_repo("renv/activate.R",  "renv/activate.R")
if (file.exists("renv/.gitignore")) copy_to_repo("renv/.gitignore", "renv/.gitignore")

message(">> Done: renv.lock, .Rprofile, renv/activate.R, docker/sysreqs.txt -> ", REPO_ROOT)
