#RAAB7 WGQ disability status and eCSC (copied from prev14 code but dropped CSC here)
# 29.06.22

raab$denom.612.persons<-(raab$x_case_612==1 | raab$y_case_612==1 | raab$z_case_612==1)+0
raab$denom.618.persons<-(raab$x_case_618==1 | raab$y_case_618==1 | raab$z_case_618==1)+0
raab$denom.660.persons<-(raab$x_case_660==1 | raab$y_case_660==1 | raab$z_case_660==1)+0
raab$denom.360.persons<-(raab$x_case_360==1 | raab$y_case_360==1 | raab$z_case_360==1)+0

raab$ecsc.618.612.num.persons<-(raab$a_case_618_612==1 | raab$b_case_618==1)+0
raab$ecsc.618.618.num.persons<-(raab$a_case_618_618==1 | raab$b_case_618==1)+0
raab$ecsc.618.660.num.persons<-(raab$a_case_618_660==1 | raab$b_case_618==1)+0
raab$ecsc.618.360.num.persons<-(raab$a_case_618_360==1 | raab$b_case_618==1)+0
raab$ecsc.612.612.num.persons<-(raab$a_case_612_612==1 | raab$b_case_612==1)+0
raab$ecsc.612.618.num.persons<-(raab$a_case_612_618==1 | raab$b_case_612==1)+0
raab$ecsc.612.660.num.persons<-(raab$a_case_612_660==1 | raab$b_case_612==1)+0
raab$ecsc.612.360.num.persons<-(raab$a_case_612_360==1 | raab$b_case_612==1)+0

raab$ecsc.660.612.num.persons<-(raab$a_case_660_612==1 | raab$b_case_660==1)+0
raab$ecsc.660.618.num.persons<-(raab$a_case_660_618==1 | raab$b_case_660==1)+0
raab$ecsc.660.660.num.persons<-(raab$a_case_660_660==1 | raab$b_case_660==1)+0
raab$ecsc.660.360.num.persons<-(raab$a_case_660_360==1 | raab$b_case_660==1)+0
raab$ecsc.360.612.num.persons<-(raab$a_case_360_612==1 | raab$b_case_360==1)+0
raab$ecsc.360.618.num.persons<-(raab$a_case_360_618==1 | raab$b_case_360==1)+0
raab$ecsc.360.660.num.persons<-(raab$a_case_360_660==1 | raab$b_case_360==1)+0
raab$ecsc.360.360.num.persons<-(raab$a_case_360_360==1 | raab$b_case_360==1)+0

# eCSC table

denom.thresh<-c(rep("612",4),rep("618",4),rep("660",4),rep("360",4))
num.thresh<-c(rep(c("ecsc_612","ecsc_618","ecsc_660","ecsc_360"),4))

wgq.ecsc<-as.data.frame(cbind(denom.thresh,num.thresh))

wgq.ecsc$any.dis.denom[wgq.ecsc$denom.thresh=="612"]<-sum(raab$x_case_612[raab$wgq.dis.any==1],na.rm=T)+sum(raab$y_case_612[raab$wgq.dis.any==1],na.rm=T)+sum(raab$z_case_612[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.denom[wgq.ecsc$denom.thresh=="618"]<-sum(raab$x_case_618[raab$wgq.dis.any==1],na.rm=T)+sum(raab$y_case_618[raab$wgq.dis.any==1],na.rm=T)+sum(raab$z_case_618[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.denom[wgq.ecsc$denom.thresh=="660"]<-sum(raab$x_case_660[raab$wgq.dis.any==1],na.rm=T)+sum(raab$y_case_660[raab$wgq.dis.any==1],na.rm=T)+sum(raab$z_case_660[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.denom[wgq.ecsc$denom.thresh=="360"]<-sum(raab$x_case_360[raab$wgq.dis.any==1],na.rm=T)+sum(raab$y_case_360[raab$wgq.dis.any==1],na.rm=T)+sum(raab$z_case_360[raab$wgq.dis.any==1],na.rm=T)

wgq.ecsc$any.non.vi.dis.denom[wgq.ecsc$denom.thresh=="612"]<-sum(raab$x_case_612[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$y_case_612[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$z_case_612[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.denom[wgq.ecsc$denom.thresh=="618"]<-sum(raab$x_case_618[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$y_case_618[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$z_case_618[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.denom[wgq.ecsc$denom.thresh=="660"]<-sum(raab$x_case_660[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$y_case_660[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$z_case_660[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.denom[wgq.ecsc$denom.thresh=="360"]<-sum(raab$x_case_360[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$y_case_360[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$z_case_360[raab$wgq.dis.nonvi==1],na.rm=T)

wgq.ecsc$no.dis.denom[wgq.ecsc$denom.thresh=="612"]<-sum(raab$x_case_612[raab$wgq.dis.any==0],na.rm=T)+sum(raab$y_case_612[raab$wgq.dis.any==0],na.rm=T)+sum(raab$z_case_612[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.denom[wgq.ecsc$denom.thresh=="618"]<-sum(raab$x_case_618[raab$wgq.dis.any==0],na.rm=T)+sum(raab$y_case_618[raab$wgq.dis.any==0],na.rm=T)+sum(raab$z_case_618[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.denom[wgq.ecsc$denom.thresh=="660"]<-sum(raab$x_case_660[raab$wgq.dis.any==0],na.rm=T)+sum(raab$y_case_660[raab$wgq.dis.any==0],na.rm=T)+sum(raab$z_case_660[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.denom[wgq.ecsc$denom.thresh=="360"]<-sum(raab$x_case_360[raab$wgq.dis.any==0],na.rm=T)+sum(raab$y_case_360[raab$wgq.dis.any==0],na.rm=T)+sum(raab$z_case_360[raab$wgq.dis.any==0],na.rm=T)

wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_612_612[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_612_618[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_612_660[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_612_360[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_618_612[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_618_618[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_618_660[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_618_360[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_660_612[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_660_618[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_660_660[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_660_360[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_360_612[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_360_618[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_360_660[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.any==1],na.rm=T)
wgq.ecsc$any.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_360_360[raab$wgq.dis.any==1],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.any==1],na.rm=T)

wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_612_612[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_612_618[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_612_660[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_612_360[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_618_612[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_618_618[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_618_660[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_618_360[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_660_612[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_660_618[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_660_660[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_660_360[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_360_612[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_360_618[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_360_660[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.nonvi==1],na.rm=T)
wgq.ecsc$any.non.vi.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_360_360[raab$wgq.dis.nonvi==1],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.nonvi==1],na.rm=T)


wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_612_612[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_612_618[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_612_660[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_612_360[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_612[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_618_612[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_618_618[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_618_660[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_618_360[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_618[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_660_612[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_660_618[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_660_660[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_660_360[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_660[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<-sum(raab$a_case_360_612[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<-sum(raab$a_case_360_618[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<-sum(raab$a_case_360_660[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.any==0],na.rm=T)
wgq.ecsc$no.dis.num[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<-sum(raab$a_case_360_360[raab$wgq.dis.any==0],na.rm=T)+sum(raab$b_case_360[raab$wgq.dis.any==0],na.rm=T)

#calculate ecsc

wgq.ecsc$any.dis.crude<-wgq.ecsc$any.dis.num/wgq.ecsc$any.dis.denom
wgq.ecsc$any.non.vi.dis.crude<-wgq.ecsc$any.non.vi.dis.num/wgq.ecsc$any.non.vi.dis.denom
wgq.ecsc$no.dis.crude<-wgq.ecsc$no.dis.num/wgq.ecsc$no.dis.denom

wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.612.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.612.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.612.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.612.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.618.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.618.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.618.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.618.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.660.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.660.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.660.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.660.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.360.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.360.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.360.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==1,],raab$ecsc.360.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1])

wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.612.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.612.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.612.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.612.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.618.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.618.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.618.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.618.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.660.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.660.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.660.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.660.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.360.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.360.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.360.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.nonvi==1,],raab$ecsc.360.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1])

wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.612.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.612.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.612.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.612.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.618.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.618.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.618.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.618.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.660.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.660.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.660.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.660.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.360.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.360.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.360.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab[raab$wgq.dis.any==0,],raab$ecsc.360.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0])

wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.660.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.660.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.660.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.660.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.360.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.360.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.360.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.360.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])

wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.660.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.660.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.660.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.660.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.360.612.num.persons[raab$wgq.dis.any==1],raab$denom.612.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.360.618.num.persons[raab$wgq.dis.any==1],raab$denom.618.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.360.660.num.persons[raab$wgq.dis.any==1],raab$denom.660.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])
wgq.ecsc$any.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$any.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.360.360.num.persons[raab$wgq.dis.any==1],raab$denom.360.persons[raab$wgq.dis.any==1],raab$clusterId[raab$wgq.dis.any==1])

wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.660.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.660.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.660.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.660.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.360.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.360.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.360.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.360.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])

wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.660.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.660.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.660.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.660.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.360.612.num.persons[raab$wgq.dis.nonvi==1],raab$denom.612.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.360.618.num.persons[raab$wgq.dis.nonvi==1],raab$denom.618.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.360.660.num.persons[raab$wgq.dis.nonvi==1],raab$denom.660.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])
wgq.ecsc$any.non.vi.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$any.non.vi.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.360.360.num.persons[raab$wgq.dis.nonvi==1],raab$denom.360.persons[raab$wgq.dis.nonvi==1],raab$clusterId[raab$wgq.dis.nonvi==1])

wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.660.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.660.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.660.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.660.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.360.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.360.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.360.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.lci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- bennett.lci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.360.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])

wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_612" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_618" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.660.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.660.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.660.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_660" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.660.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="612"],raab$ecsc.360.612.num.persons[raab$wgq.dis.any==0],raab$denom.612.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="618"],raab$ecsc.360.618.num.persons[raab$wgq.dis.any==0],raab$denom.618.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="660"],raab$ecsc.360.660.num.persons[raab$wgq.dis.any==0],raab$denom.660.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])
wgq.ecsc$no.dis.adjusted.uci[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"]<- bennett.uci(wgq.ecsc$no.dis.adjusted[wgq.ecsc$num.thresh=="ecsc_360" & wgq.ecsc$denom.thresh=="360"],raab$ecsc.360.360.num.persons[raab$wgq.dis.any==0],raab$denom.360.persons[raab$wgq.dis.any==0],raab$clusterId[raab$wgq.dis.any==0])

lcis<-grep("lci",names(wgq.ecsc))
ucis<-grep("uci",names(wgq.ecsc))
wgq.ecsc[,lcis][wgq.ecsc[,lcis]<0]<-0
wgq.ecsc[,ucis][wgq.ecsc[,ucis]>1]<-1

apcts<-grep("adjusted",names(wgq.ecsc))
wgq.ecsc[,apcts] <- round( wgq.ecsc[,apcts] * 100, 1)
wgq.ecsc[,apcts] <- format( wgq.ecsc[,apcts], nsmall=1)

cpcts<-grep("crude",names(wgq.ecsc))
wgq.ecsc[,cpcts] <- round( wgq.ecsc[,cpcts] * 100, 1)
wgq.ecsc[,cpcts] <- format( wgq.ecsc[,cpcts], nsmall=1)

