# output required in summary_out.csv for equity figure on raab.world

# sex-adjusted eCSC by age groups (age_50_64 or age_65_plus)
# equity figure only reports <6/12 and <6/60

raab$denom.612.persons<-(raab$x_case_612==1 | raab$y_case_612==1 | raab$z_case_612==1)+0
raab$denom.618.persons<-(raab$x_case_618==1 | raab$y_case_618==1 | raab$z_case_618==1)+0
raab$denom.660.persons<-(raab$x_case_660==1 | raab$y_case_660==1 | raab$z_case_660==1)+0
raab$denom.360.persons<-(raab$x_case_360==1 | raab$y_case_360==1 | raab$z_case_360==1)+0

raab$ecsc.618.612.num.persons<-(raab$a_case_618_612==1 | raab$b_case_618==1)+0
raab$ecsc.618.618.num.persons<-(raab$a_case_618_618==1 | raab$b_case_618==1)+0
raab$ecsc.618.660.num.persons<-(raab$a_case_618_660==1 | raab$b_case_618==1)+0
raab$ecsc.618.360.num.persons<-(raab$a_case_618_360==1 | raab$b_case_618==1)+0
raab$ecsc.612.612.num.persons<-(raab$a_case_612_612==1 | raab$b_case_612==1)+0
raab$ecsc.612.618.num.persons<-(raab$a_case_612_618==1 | raab$b_case_612==1)+0
raab$ecsc.612.660.num.persons<-(raab$a_case_612_660==1 | raab$b_case_612==1)+0
raab$ecsc.612.360.num.persons<-(raab$a_case_612_360==1 | raab$b_case_612==1)+0

raab$csc.612.num.persons<-(raab$x_case_612==1 | raab$y_case_612==1)+0
raab$csc.618.num.persons<-(raab$x_case_618==1 | raab$y_case_618==1)+0
raab$csc.660.num.persons<-(raab$x_case_660==1 | raab$y_case_660==1)+0
raab$csc.360.num.persons<-(raab$x_case_360==1 | raab$y_case_360==1)+0

#CSC and eCSC table
denom.thresh<-c(rep("612",3),rep("618",3),rep("660",3),rep("360",3))
unique.denom.thresh<-unique(denom.thresh)
num.thresh<-c(rep(c("csc","ecsc_612","ecsc_618"),4))
unique.num.thresh<-unique(num.thresh)

#CSC only table
#denom.thresh<-c("612","618","660","360")
#num.thresh<-rep("csc",4)

equity.ecsc.age<-as.data.frame(cbind(denom.thresh,num.thresh))

equity.ecsc.age$age_50_64.denom[equity.ecsc.age$denom.thresh=="612"]<-sum(raab$denom.612.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.denom[equity.ecsc.age$denom.thresh=="618"]<-sum(raab$denom.618.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.denom[equity.ecsc.age$denom.thresh=="660"]<-sum(raab$denom.660.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.denom[equity.ecsc.age$denom.thresh=="360"]<-sum(raab$denom.360.persons[raab$age.groups.working=="age_50_64"],na.rm=T)

equity.ecsc.age$age_65_plus.denom[equity.ecsc.age$denom.thresh=="612"]<-sum(raab$denom.612.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.denom[equity.ecsc.age$denom.thresh=="618"]<-sum(raab$denom.618.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.denom[equity.ecsc.age$denom.thresh=="660"]<-sum(raab$denom.660.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.denom[equity.ecsc.age$denom.thresh=="360"]<-sum(raab$denom.360.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)

equity.ecsc.age$total.denom[equity.ecsc.age$denom.thresh=="612"]<-sum(raab$denom.612.persons,na.rm=T)
equity.ecsc.age$total.denom[equity.ecsc.age$denom.thresh=="618"]<-sum(raab$denom.618.persons,na.rm=T)
equity.ecsc.age$total.denom[equity.ecsc.age$denom.thresh=="660"]<-sum(raab$denom.660.persons,na.rm=T)
equity.ecsc.age$total.denom[equity.ecsc.age$denom.thresh=="360"]<-sum(raab$denom.360.persons,na.rm=T)

equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$csc.612.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$csc.618.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$csc.660.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$csc.360.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$ecsc.612.612.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$ecsc.612.618.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$ecsc.612.660.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$ecsc.612.360.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$ecsc.618.612.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$ecsc.618.618.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$ecsc.618.660.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)
equity.ecsc.age$age_50_64.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$ecsc.618.360.num.persons[raab$age.groups.working=="age_50_64"],na.rm=T)

equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$csc.612.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$csc.618.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$csc.660.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$csc.360.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$ecsc.612.612.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$ecsc.612.618.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$ecsc.612.660.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$ecsc.612.360.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$ecsc.618.612.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$ecsc.618.618.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$ecsc.618.660.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)
equity.ecsc.age$age_65_plus.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$ecsc.618.360.num.persons[raab$age.groups.working=="age_65_plus"],na.rm=T)

equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$csc.612.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$csc.618.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$csc.660.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$csc.360.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$ecsc.612.612.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$ecsc.612.618.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$ecsc.612.660.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$ecsc.612.360.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<-sum(raab$ecsc.618.612.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<-sum(raab$ecsc.618.618.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<-sum(raab$ecsc.618.660.num.persons,na.rm=T)
equity.ecsc.age$total.num[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<-sum(raab$ecsc.618.360.num.persons,na.rm=T)

#calculate csc

equity.ecsc.age$age_50_64.crude<-equity.ecsc.age$age_50_64.num/equity.ecsc.age$age_50_64.denom
equity.ecsc.age$age_65_plus.crude<-equity.ecsc.age$age_65_plus.num/equity.ecsc.age$age_65_plus.denom
equity.ecsc.age$total.crude<-equity.ecsc.age$total.num/equity.ecsc.age$total.denom

equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$csc.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$csc.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$csc.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$csc.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$ecsc.612.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$ecsc.612.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$ecsc.612.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$ecsc.612.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$ecsc.618.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$ecsc.618.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$ecsc.618.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- prop.sex.adjust(age.5064.subpop,raab[raab$age.groups.working=="age_50_64",],raab$ecsc.618.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"])

equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$csc.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$csc.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$csc.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$csc.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$ecsc.612.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$ecsc.612.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$ecsc.612.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$ecsc.612.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$ecsc.618.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$ecsc.618.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$ecsc.618.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- prop.sex.adjust(age.65p.subpop,raab[raab$age.groups.working=="age_65_plus",],raab$ecsc.618.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"])

equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab,raab$csc.612.num.persons,raab$denom.612.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab,raab$csc.618.num.persons,raab$denom.618.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab,raab$csc.660.num.persons,raab$denom.660.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab,raab$csc.360.num.persons,raab$denom.360.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab,raab$ecsc.612.612.num.persons,raab$denom.612.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab,raab$ecsc.612.618.num.persons,raab$denom.618.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab,raab$ecsc.612.660.num.persons,raab$denom.660.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab,raab$ecsc.612.360.num.persons,raab$denom.360.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- prop.age.sex.adjust(popfives,raab,raab$ecsc.618.612.num.persons,raab$denom.612.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- prop.age.sex.adjust(popfives,raab,raab$ecsc.618.618.num.persons,raab$denom.618.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- prop.age.sex.adjust(popfives,raab,raab$ecsc.618.660.num.persons,raab$denom.660.persons)
equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- prop.age.sex.adjust(popfives,raab,raab$ecsc.618.360.num.persons,raab$denom.360.persons)

equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"],raab$csc.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"],raab$csc.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"],raab$csc.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"],raab$csc.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])

equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"],raab$csc.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"],raab$csc.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"],raab$csc.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"],raab$csc.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.612.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.618.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.660.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])
equity.ecsc.age$age_50_64.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$age_50_64.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$age.groups.working=="age_50_64"],raab$denom.360.persons[raab$age.groups.working=="age_50_64"],raab$clusterId[raab$age.groups.working=="age_50_64"])

equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"],raab$csc.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"],raab$csc.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"],raab$csc.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"],raab$csc.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])

equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"],raab$csc.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"],raab$csc.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"],raab$csc.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"],raab$csc.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.612.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.612.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.612.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.612.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.618.612.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.612.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.618.618.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.618.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.618.660.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.660.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])
equity.ecsc.age$age_65_plus.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$age_65_plus.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.618.360.num.persons[raab$age.groups.working=="age_65_plus"],raab$denom.360.persons[raab$age.groups.working=="age_65_plus"],raab$clusterId[raab$age.groups.working=="age_65_plus"])

equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"],raab$csc.612.num.persons,raab$denom.612.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"],raab$csc.618.num.persons,raab$denom.618.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"],raab$csc.660.num.persons,raab$denom.660.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"],raab$csc.360.num.persons,raab$denom.360.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.612.612.num.persons,raab$denom.612.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.612.618.num.persons,raab$denom.618.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.612.660.num.persons,raab$denom.660.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.612.360.num.persons,raab$denom.360.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.618.612.num.persons,raab$denom.612.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.618.618.num.persons,raab$denom.618.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.618.660.num.persons,raab$denom.660.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.lci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- bennett.lci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.618.360.num.persons,raab$denom.360.persons,raab$clusterId)

equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="612"],raab$csc.612.num.persons,raab$denom.612.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="618"],raab$csc.618.num.persons,raab$denom.618.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="660"],raab$csc.660.num.persons,raab$denom.660.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="csc" & equity.ecsc.age$denom.thresh=="360"],raab$csc.360.num.persons,raab$denom.360.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.612.612.num.persons,raab$denom.612.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.612.618.num.persons,raab$denom.618.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.612.660.num.persons,raab$denom.660.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_612" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.612.360.num.persons,raab$denom.360.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="612"],raab$ecsc.618.612.num.persons,raab$denom.612.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="618"],raab$ecsc.618.618.num.persons,raab$denom.618.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="660"],raab$ecsc.618.660.num.persons,raab$denom.660.persons,raab$clusterId)
equity.ecsc.age$total.adjusted.uci[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"]<- bennett.uci(equity.ecsc.age$total.adjusted[equity.ecsc.age$num.thresh=="ecsc_618" & equity.ecsc.age$denom.thresh=="360"],raab$ecsc.618.360.num.persons,raab$denom.360.persons,raab$clusterId)

equity.ecsc.age$quality_gap<-NA

equity.ecsc.age$quality_gap[equity.ecsc.age$denom.thresh=="612" & equity.ecsc.age$num.thresh=="ecsc_612"]<-(equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="612" & equity.ecsc.age$num.thresh=="csc"]-equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="612" & equity.ecsc.age$num.thresh=="ecsc_612"])/equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="612" & equity.ecsc.age$num.thresh=="csc"]
equity.ecsc.age$quality_gap[equity.ecsc.age$denom.thresh=="618" & equity.ecsc.age$num.thresh=="ecsc_612"]<-(equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="618" & equity.ecsc.age$num.thresh=="csc"]-equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="618" & equity.ecsc.age$num.thresh=="ecsc_612"])/equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="618" & equity.ecsc.age$num.thresh=="csc"]
equity.ecsc.age$quality_gap[equity.ecsc.age$denom.thresh=="660" & equity.ecsc.age$num.thresh=="ecsc_612"]<-(equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="660" & equity.ecsc.age$num.thresh=="csc"]-equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="660" & equity.ecsc.age$num.thresh=="ecsc_612"])/equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="660" & equity.ecsc.age$num.thresh=="csc"]
equity.ecsc.age$quality_gap[equity.ecsc.age$denom.thresh=="360" & equity.ecsc.age$num.thresh=="ecsc_612"]<-(equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="360" & equity.ecsc.age$num.thresh=="csc"]-equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="360" & equity.ecsc.age$num.thresh=="ecsc_612"])/equity.ecsc.age$total.adjusted[equity.ecsc.age$denom.thresh=="360" & equity.ecsc.age$num.thresh=="csc"]

lcis<-grep("lci",names(equity.ecsc.age))
ucis<-grep("uci",names(equity.ecsc.age))
equity.ecsc.age[,lcis][equity.ecsc.age[,lcis]<0]<-0
equity.ecsc.age[,ucis][equity.ecsc.age[,ucis]>1]<-1

apcts<-grep("adjusted",names(equity.ecsc.age))
equity.ecsc.age[,apcts] <- round( equity.ecsc.age[,apcts] * 100, 1)
equity.ecsc.age[,apcts] <- format( equity.ecsc.age[,apcts], nsmall=1)

cpcts<-grep("crude",names(equity.ecsc.age))
equity.ecsc.age[,cpcts] <- round( equity.ecsc.age[,cpcts] * 100, 1)
equity.ecsc.age[,cpcts] <- format( equity.ecsc.age[,cpcts], nsmall=1)

equity.ecsc.age$quality_gap <- round( equity.ecsc.age$quality_gap * 100, 1)
equity.ecsc.age$quality_gap[is.na(equity.ecsc.age$quality_gap)]<-""
equity.ecsc.age$quality_gap <- format( equity.ecsc.age$quality_gap, nsmall=1)
